backend:
  name: github
  repo: aej11a/hoboken-parking-netlify

media_folder: static/assets
public_folder: assets

collections:
  - name: info
    label: Info
    folder: info
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }